"""Hospital-specific specialist allocation for hospital id 2."""

from copy import deepcopy

from master_config import symptom_to_specialist as DEFAULT_SYMPTOM_TO_SPECIALIST

# symptom_specialist_map.py
# Mapping from symptom -> specialist.
# Rule: If multiple specialists are listed, we ALWAYS take the first one.

HOSPITAL_2_SPECIALIST_OVERRIDES = {
    "acidity": "Gastroenterology",
    "acne": "Dermatology",
    "allergy": "Dermatology",
    "animal bite": "General Surgery",
    "ankle bleeding": "Orthopaedics",
    "ankle injury": "Orthopaedics",
    "ankle pain": "Orthopaedics",
    "ankle stiffness": "Orthopaedics",
    "ankle swelling": "Orthopaedics",
    "ankle weakness": "Orthopaedics",
    "anxiety": "Psychiatry",
    "appendicitis": "General Surgery",
    "arm boils": "Dermatology",
    "arm injury": "Orthopaedics",
    "arm itching": "Dermatology",
    "arm lump": "General Medicine",
    "arm numbness": "Neurology",
    "arm pain": "Orthopaedics",
    "arm spasm": "General Medicine",
    "arm swelling": "Orthopaedics",
    "arm weakness": "Orthopaedics",
    "arthritis": "General Medicine",
    "asthma": "Pulmonology",
    "back boils": "Dermatology",
    "back injury": "Orthopaedics",
    "back issue": "General Medicine",
    "back itching": "Dermatology",
    "back lump": "General Medicine",
    "back numbness": "Neurology",
    "back pain": "Orthopaedics",
    "back spasm": "General Medicine",
    "back stiffness": "Orthopaedics",
    "back weakness": "Orthopaedics",
    "balance problem": "General Medicine",
    "bleeding": "General Surgery",
    "blister": "General Medicine",
    "bloating": "General Medicine",
    "blood in stool": "General Medicine",
    "blood in urine": "Urology",
    "blurred vision": "Ophthalmology",
    "body boils": "Dermatology",
    "body cut": "Orthopaedics",
    "body fatigue": "General Medicine",
    "body itching": "Dermatology",
    "body lump": "General Medicine",
    "body pain": "General Medicine",
    "body stiffness": "General Medicine",
    "body swelling": "General Medicine",
    "body weakness": "General Medicine",
    "bone fracture": "Orthopaedics",
    "bone injury": "Orthopaedics",
    "bone pain": "General Medicine",
    "bone swelling": "General Medicine",
    "bone weakness": "General Medicine",
    "brittle nails": "General Medicine",
    "broken voice": "General Medicine",
    "bruises": "General Medicine",
    "caesarean section": "Obstetrics and Gynecology",
    "calf injury": "Orthopaedics",
    "calf pain": "Orthopaedics",
    "calf spasm": "General Medicine",
    "calf swelling": "Orthopaedics",
    "calf weakness": "Orthopaedics",
    "cardiac surgery": "CTVS",
    "cheek cut": "Orthopaedics",
    "cheek injury": "Orthopaedics",
    "cheek numbness": "Neurology",
    "cheek pain": "General Medicine",
    "cheek redness": "Ophthalmology",
    "cheek swelling": "General Medicine",
    "chest boils": "Dermatology",
    "chest breathing": "General Medicine",
    "chest discomfort": "General Medicine",
    "chest itching": "Dermatology",
    "chest lump": "General Medicine",
    "chest pain": "Cardiology",
    "chest palpitations": "Cardiology",
    "chest weakness": "General Medicine",
    "chickenpox": "General Medicine",
    "child bleeding": "Pediatric Surgery",
    "child default": "General Medicine",
    "child pain": "General Medicine",
    "chills": "General Medicine",
    "chin cut": "Orthopaedics",
    "chin injury": "Orthopaedics",
    "chin lump": "General Medicine",
    "chin numbness": "Neurology",
    "chin pain": "General Medicine",
    "chin swelling": "General Medicine",
    "cholesterol": "General Medicine",
    "cholestrol": "General Medicine",
    "cold": "General Medicine",
    "cold intolerance": "General Medicine",
    "confusion": "General Medicine",
    "congestion": "General Medicine",
    "constipation": "Gastroenterology",
    "cough": "Pulmonology",
    "covid": "General Medicine",
    "cramp": "General Medicine",
    "dandruff": "Dermatology",
    "dehydration": "General Medicine",
    "dengue": "General Medicine",
    "depression": "Psychiatry",
    "diabetes": "Endocrinology",
    "diarrhea": "Gastroenterology",
    "difficulty concentrating": "General Medicine",
    "difficulty speaking": "General Medicine",
    "difficulty swallowing": "General Medicine",
    "dizziness": "Neurology",
    "dry mouth": "General Medicine",
    "dysentery": "General Medicine",
    "ear bleeding": "Neurosurgery",
    "ear discharge": "ENT",
    "ear freeze": "General Medicine",
    "ear hearing loss": "General Medicine",
    "ear infection": "General Medicine",
    "ear itching": "Dermatology",
    "ear pain": "ENT",
    "ear ringing": "General Medicine",
    "elbow boils": "Dermatology",
    "elbow injury": "Orthopaedics",
    "elbow lump": "Orthopaedics",
    "elbow pain": "Orthopaedics",
    "elbow stiffness": "Orthopaedics",
    "elbow swelling": "Orthopaedics",
    "elbow weakness": "Orthopaedics",
    "excessive thirst": "General Medicine",
    "exhaustion": "General Medicine",
    "eye blurry vision": "Ophthalmology",
    "eye burn": "Ophthalmology",
    "eye crushing": "Ophthalmology",
    "eye discharge": "Ophthalmology",
    "eye itching": "Dermatology",
    "eye pain": "Ophthalmology",
    "eye redness": "Ophthalmology",
    "eye sight issues": "Ophthalmology",
    "eye swelling": "Ophthalmology",
    "eye weakness": "Ophthalmology",
    "face boils": "Dermatology",
    "face cut": "Orthopaedics",
    "face drooping": "Neurology",
    "face injury": "Orthopaedics",
    "face itching": "Dermatology",
    "face lump": "General Medicine",
    "face numbness": "Neurology",
    "face pain": "General Medicine",
    "face swelling": "General Medicine",
    "fainting": "Neurology",
    "fatigue": "General Medicine",
    "fatty liver": "General Medicine",
    "female issue": "Obstetrics and Gynecology",
    "female reproductive issues": "Obstetrics and Gynecology",
    "fever": "General Medicine",
    "finger bleeding": "Orthopaedics",
    "finger cut": "Orthopaedics",
    "finger freeze": "General Medicine",
    "finger injury": "Orthopaedics",
    "finger itching": "Dermatology",
    "finger numbness": "Neurology",
    "finger pain": "Orthopaedics",
    "finger stiffness": "Orthopaedics",
    "finger swelling": "Orthopaedics",
    "flu": "General Medicine",
    "foot bleeding": "Orthopaedics",
    "foot boils": "Dermatology",
    "foot burning": "General Medicine",
    "foot cut": "Orthopaedics",
    "foot freeze": "General Medicine",
    "foot injury": "Orthopaedics",
    "foot itching": "Dermatology",
    "foot lump": "General Medicine",
    "foot numbness": "Neurology",
    "foot pain": "Orthopaedics",
    "foot spasm": "General Medicine",
    "foot stiffness": "Orthopaedics",
    "foot swelling": "Orthopaedics",
    "foot weakness": "Orthopaedics",
    "forehead boils": "Dermatology",
    "forehead cut": "Orthopaedics",
    "forehead injury": "Orthopaedics",
    "forehead lump": "General Medicine",
    "forehead pain": "General Medicine",
    "forehead swelling": "General Medicine",
    "forehead tingling": "General Medicine",
    "fracture": "Orthopaedics",
    "frequent urination": "General Medicine",
    "gallstones": "Urology",
    "gas": "General Medicine",
    "genital bleeding": "General Surgery",
    "genital discharge": "General Medicine",
    "genital discomfort": "General Medicine",
    "genital erection": "General Medicine",
    "genital itching": "Dermatology",
    "genital pain": "General Medicine",
    "genital swelling": "General Medicine",
    "goiter": "General Medicine",
    "gout": "General Medicine",
    "hair cut": "Dermatology",
    "hair dandruff": "Dermatology",
    "hair dryness": "Dermatology",
    "hair greying": "Dermatology",
    "hair itching": "Dermatology",
    "hair loss": "Dermatology",
    "hallucination": "General Medicine",
    "hand bleeding": "Orthopaedics",
    "hand boils": "Dermatology",
    "hand dryness": "General Medicine",
    "hand freeze": "General Medicine",
    "hand injury": "Orthopaedics",
    "hand itching": "Dermatology",
    "hand lump": "General Medicine",
    "hand numbness": "Neurology",
    "hand pain": "Orthopaedics",
    "hand swelling": "Orthopaedics",
    "hand weakness": "Orthopaedics",
    "head injury": "Orthopaedics",
    "head itching": "Dermatology",
    "head numbness": "Neurology",
    "head pain": "Neurology",
    "head pressure": "Neurology",
    "headache": "Neurology",
    "hearing loss": "ENT",
    "heart attack": "Cardiology",
    "heart burn": "General Medicine",
    "heart pain": "Cardiology",
    "heart palpitation": "Cardiology",
    "heart problem": "Cardiology",
    "heart surgery": "Cardiology",
    "heart weakness": "Cardiology",
    "heel bleeding": "General Surgery",
    "heel cut": "Orthopaedics",
    "heel injury": "Orthopaedics",
    "heel numbness": "Neurology",
    "heel pain": "General Medicine",
    "heel stiffness": "General Medicine",
    "heel swelling": "General Medicine",
    "hernia": "General Surgery",
    "hiccups": "General Medicine",
    "high blood pressure": "General Medicine",
    "hip injury": "Orthopaedics",
    "hip itching": "Dermatology",
    "hip pain": "Orthopaedics",
    "hip stiffness": "Orthopaedics",
    "hip swelling": "Orthopaedics",
    "hip weakness": "Orthopaedics",
    "hydrocele": "General Medicine",
    "indigestion": "General Medicine",
    "infection": "General Medicine",
    "inflammation": "General Medicine",
    "injury": "Orthopaedics",
    "insomnia": "Psychiatry",
    "irregular heartbeat": "Cardiology",
    "irritation": "General Medicine",
    "itching": "Dermatology",
    "jaundice": "General Medicine",
    "jaw cut": "Orthopaedics",
    "jaw injury": "Orthopaedics",
    "jaw pain": "General Medicine",
    "jaw swelling": "General Medicine",
    "joint boils": "Dermatology",
    "joint injury": "Orthopaedics",
    "joint lump": "General Medicine",
    "joint numbness": "Neurology",
    "joint pain": "Orthopaedics",
    "joint stiffness": "Orthopaedics",
    "joint swelling": "Orthopaedics",
    "joint weakness": "Orthopaedics",
    "kidney issue": "Urology",
    "knee boils": "Dermatology",
    "knee cut": "Orthopaedics",
    "knee freeze": "General Medicine",
    "knee injury": "Orthopaedics",
    "knee itching": "Dermatology",
    "knee lump": "General Medicine",
    "knee numbness": "Neurology",
    "knee pain": "Orthopaedics",
    "knee soreness": "General Medicine",
    "knee stiffness": "Orthopaedics",
    "knee swelling": "Orthopaedics",
    "knee weakness": "Orthopaedics",
    "lack of motivation": "Psychiatry",
    "latrine issue": "General Medicine",
    "leg bleeding": "Orthopaedics",
    "leg boils": "Dermatology",
    "leg freeze": "General Medicine",
    "leg injury": "Orthopaedics",
    "leg itching": "Dermatology",
    "leg lump": "General Medicine",
    "leg numbness": "Neurology",
    "leg pain": "Orthopaedics",
    "leg spasm": "General Medicine",
    "leg swelling": "Orthopaedics",
    "leg weakness": "Orthopaedics",
    "lip boils": "Dermatology",
    "lip cut": "General Surgery",
    "lip dryness": "General Medicine",
    "lip lump": "General Surgery",
    "lip numbness": "Neurology",
    "lip pain": "General Medicine",
    "lip swelling": "General Medicine",
    "lip ulcers": "Gastroenterology",
    "liver issue": "General Medicine",
    "loss of appetite": "General Medicine",
    "low blood pressure": "General Medicine",
    "malaria": "General Medicine",
    "male reproductive issues": "General Medicine",
    "memory loss": "General Medicine",
    "menopause": "Gynecology",
    "migraine": "Neurology",
    "mood swing": "General Medicine",
    "more hungry": "General Medicine",
    "mouth bad breath": "General Medicine",
    "mouth bleeding": "General Surgery",
    "mouth cut": "Orthopaedics",
    "mouth dryness": "General Medicine",
    "mouth itching": "Dermatology",
    "mouth numbness": "Neurology",
    "mouth pain": "General Medicine",
    "mouth swelling": "General Medicine",
    "mouth ulcer": "Gastroenterology",
    "muscle cramps": "General Medicine",
    "muscle injury": "Orthopaedics",
    "muscle itching": "Dermatology",
    "muscle numbness": "Neurology",
    "muscle pain": "General Medicine",
    "muscle pulling": "General Medicine",
    "muscle spasm": "General Medicine",
    "muscle swelling": "General Medicine",
    "muscle weakness": "General Medicine",
    "nails brittle": "General Medicine",
    "nails cut": "Orthopaedics",
    "nails discoloration": "General Medicine",
    "nails growth": "General Medicine",
    "nails infection": "Dermatology",
    "nails pain": "General Medicine",
    "nausea": "General Medicine",
    "neck bleeding": "Orthopaedics",
    "neck boils": "Dermatology",
    "neck cut": "Orthopaedics",
    "neck injury": "Orthopaedics",
    "neck itching": "Dermatology",
    "neck lump": "General Medicine",
    "neck numbness": "Neurology",
    "neck pain": "Orthopaedics",
    "neck spasm": "General Medicine",
    "neck stiffness": "Orthopaedics",
    "neck swelling": "Orthopaedics",
    "neck weakness": "Orthopaedics",
    "nervousness": "Neurology",
    "neurosurgery": "neurosurgery",
    "nose bleed": "ENT",
    "nose boils": "Dermatology",
    "nose burning": "ENT",
    "nose congestion": "ENT",
    "nose cut": "ENT",
    "nose freeze": "ENT",
    "nose infection": "ENT",
    "nose injury": "Orthopaedics",
    "nose itching": "Dermatology",
    "nose lump": "ENT",
    "nose pain": "ENT",
    "nose sniffing": "ENT",
    "nosebleed": "ENT",
    "numbness": "Neurology",
    "obesity": "Endocrinology",
    "operation": "General Medicine",
    "palm cut": "Orthopaedics",
    "palm dryness": "General Medicine",
    "palm injury": "Orthopaedics",
    "palm itching": "Dermatology",
    "palm numbness": "Neurology",
    "palm pain": "General Medicine",
    "palm stiffness": "General Medicine",
    "palm swelling": "General Medicine",
    "panic attack": "Psychiatry",
    "pelvic injury": "Orthopaedics",
    "pelvic itching": "Dermatology",
    "pelvic numbness": "Neurology",
    "pelvic pain": "General Medicine",
    "pelvic stiffness": "General Medicine",
    "pelvic swelling": "General Medicine",
    "pelvic weakness": "General Medicine",
    "penis bleeding": "General Surgery",
    "penis discharge": "Dermatology",
    "penis discomfort": "Andrology",
    "penis erection": "General Medicine",
    "penis itching": "Dermatology",
    "penis pain": "General Medicine",
    "penis swelling": "General Medicine",
    "period bleeding": "Obstetrics & Gynaecology",
    "period default": "Obstetrics & Gynaecology",
    "period delayed": "Obstetrics & Gynaecology",
    "period pain": "Obstetrics & Gynaecology",
    "piles": "General Surgery",
    "pneumonia": "General Medicine",
    "pregnancy": "Obstetrics & Gynaecology",
    "rapid breathing": "Pulmonology",
    "rash": "Dermatology",
    "restlessness": "General Medicine",
    "ringworm": "General Medicine",
    "runny nose": "ENT",
    "seizures": "Neurology",
    "shortness of breath": "Pulmonology",
    "shoulder boils": "Dermatology",
    "shoulder cut": "Orthopaedics",
    "shoulder injury": "Orthopaedics",
    "shoulder itching": "Dermatology",
    "shoulder lump": "General Medicine",
    "shoulder numbness": "Neurology",
    "shoulder pain": "Orthopaedics",
    "shoulder stiffness": "Orthopaedics",
    "shoulder weakness": "Orthopaedics",
    "skin acne": "Dermatology",
    "skin bleeding": "General Surgery",
    "skin boils": "Dermatology",
    "skin burn": "General Surgery",
    "skin burning": "General Surgery",
    "skin cut": "General Surgery",
    "skin discoloration": "General Medicine",
    "skin dryness": "Dermatology",
    "skin infection": "Dermatology",
    "skin itching": "Dermatology",
    "skin lump": "Dermatology",
    "skin rash": "Dermatology",
    "skin swelling": "Dermatology",
    "sleepy": "General Medicine",
    "slow reflexes": "Neurology",
    "sneezing": "Allergy & Immunology",
    "soles cracks": "General Medicine",
    "soles itching": "Dermatology",
    "soles numbness": "Neurology",
    "soles pain": "General Medicine",
    "soles swelling": "General Medicine",
    "sprain": "Orthopaedics",
    "stomach bloating": "Gastroenterology",
    "stomach boils": "Dermatology",
    "stomach burning": "Gastroenterology",
    "stomach lump": "Gastroenterology",
    "stomach pain": "Gastroenterology",
    "stomach swelling": "Gastroenterology",
    "stomach weakness": "Gastroenterology",
    "strain": "General Medicine",
    "stress": "Psychiatry",
    "sugar": "General Medicine",
    "sweat": "General Medicine",
    "swelling": "General Medicine",
    "swollen lymph nodes": "General Medicine",
    "testicle bleeding": "General Surgery",
    "testicle itching": "Dermatology",
    "testicle problem": "General Medicine",
    "testicle swelling": "General Surgery",
    "thigh boils": "Dermatology",
    "thigh cut": "Orthopaedics",
    "thigh injury": "Orthopaedics",
    "thigh itching": "Dermatology",
    "thigh lump": "General Medicine",
    "thigh numbness": "Neurology",
    "thigh pain": "Orthopaedics",
    "thigh spasm": "General Medicine",
    "thigh swelling": "Orthopaedics",
    "thigh weakness": "Orthopaedics",
    "throat boils": "ENT",
    "throat difficulty_swallowing": "ENT",
    "throat dryness": "ENT",
    "throat hoarseness": "ENT",
    "throat infection": "ENT",
    "throat itching": "ENT",
    "throat lump": "ENT",
    "throat pain": "ENT",
    "throat swelling": "ENT",
    "thumb bleeding": "General Surgery",
    "thumb cut": "Orthopaedics",
    "thumb injury": "Orthopaedics",
    "thumb numbness": "Neurology",
    "thumb pain": "Orthopaedics",
    "thumb stiffness": "Orthopaedics",
    "thumb swelling": "Orthopaedics",
    "thyroid": "ENT",
    "tingling": "General Medicine",
    "toe bleeding": "Orthopaedics",
    "toe cut": "Orthopaedics",
    "toe freeze": "General Medicine",
    "toe injury": "Orthopaedics",
    "toe numbness": "Neurology",
    "toe pain": "Orthopaedics",
    "toe stiffness": "Orthopaedics",
    "toe swelling": "Orthopaedics",
    "toes cut": "Orthopaedics",
    "toes injury": "Orthopaedics",
    "toes pain": "Orthopaedics",
    "toes swelling": "Orthopaedics",
    "tongue burning": "ENT",
    "tongue cut": "ENT",
    "tongue pain": "ENT",
    "tongue swelling": "ENT",
    "tongue ulcers": "ENT",
    "tooth broken": "ORAL & MAXILLOFACIAL SURGERY",
    "tooth decay": "Dentist",
    "tooth injury": "Dentist",
    "tooth pain": "Dentist",
    "tooth sensitivity": "Dentist",
    "tooth tingling": "Dentist",
    "tremor": "General Medicine",
    "typhoid": "General Medicine",
    "ulcers": "Gastroenterology",
    "urinary blood": "Urology",
    "urinary burn": "Urology",
    "urinary difficulty": "Urology",
    "urinary frequency": "Urology",
    "urinary pain": "Urology",
    "urine issue": "Urology",
    "vomiting": "Gastroenterology",
    "waist injury": "Orthopaedics",
    "waist itching": "Dermatology",
    "waist numbness": "Neurology",
    "waist pain": "General Medicine",
    "waist stiffness": "General Medicine",
    "waist swelling": "General Medicine",
    "waist weakness": "General Medicine",
    "weakness": "General Medicine",
    "weight gain": "General Medicine",
    "weight issue": "General Medicine",
    "weight loss": "Endocrinology",
    "wound": "Orthopaedics",
    "wrist injury": "Orthopaedics",
    "wrist numbness": "Neurology",
    "wrist pain": "Orthopaedics",
    "wrist stiffness": "Orthopaedics",
    "wrist swelling": "Orthopaedics",
    "wrist weakness": "Orthopaedics",
}

HOSPITAL_SPECIALIST_OVERRIDES = {
    5: HOSPITAL_2_SPECIALIST_OVERRIDES,
}

def _normalize_hospital_id(hospital_id):
    """Try to normalise *hospital_id* to an ``int`` when possible."""

    try:
        return int(hospital_id)
    except (TypeError, ValueError):
        return hospital_id


def get_hospital_specific_mapping(hospital_id):
    """Return the specialist map tailored for *hospital_id*.

    When no overrides exist for the requested hospital, the default mapping
    from :mod:`master_config` is returned.
    """

    normalized_id = _normalize_hospital_id(hospital_id)
    overrides = HOSPITAL_SPECIALIST_OVERRIDES.get(normalized_id)
    if not overrides:
        return DEFAULT_SYMPTOM_TO_SPECIALIST

    mapping = deepcopy(DEFAULT_SYMPTOM_TO_SPECIALIST)
    for symptom, specialist in overrides.items():
        mapping[symptom.lower()] = specialist
    return mapping


__all__ = [
    "get_hospital_specific_mapping",
    "HOSPITAL_2_SPECIALIST_OVERRIDES",
    "HOSPITAL_SPECIALIST_OVERRIDES",
]
